### ISSUE TITLE
win10无法使用插件

### ISSUE THREAD

**Issue by kzy77** [tinet-jutt/ImageToText#1]
报错信息如下：
`(node:11428) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
d:\Users\foo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
Congratulations, your extension "image-to-text" is now active!
d:\Users\foo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
9
error: Error: ENOENT: no such file or directory, open
	at Object.openSync (fs.js:476:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
	at Object.readFileSync (fs.js:377:35)
	at Object.readFileSync (electron/js2c/asar_bundle.js:5:8872)
	at e:\CODE\ImageToText\dist\extension.js:46:31
	at Generator.next (<anonymous>)
	at fulfilled (e:\CODE\ImageToText\dist\extension.js:11:58)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
d:\Users\foo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5`

debug插件定位问题在src\extension.ts文件中29号，const bitmap = fs.readFileSync(imageList[0]);

另外C:\Users\foo\AppData\Local\Temp\image-to-text目录下没有任何文件

**Comment by tinet-jutt** [comment]
这个报错不影响使用，win10下尝试过没问题啊，排除下是否是外部因素引起的
